# Generated by Django 4.1.2 on 2022-10-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='ppg',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
