# Generated by Django 4.1.2 on 2022-10-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teams_alter_player_ppg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
