# Generated by Django 4.1.2 on 2022-10-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='city',
            new_name='cityOfTeam',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='nameOfTeam',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='year',
            new_name='yearBorn',
        ),
    ]
